### ISSUE TITLE
Typo in script help

### ISSUE THREAD

**Issue by Adreitz** [MegaByte/jpegultrascan#4]
The script help states:

  -b 0-3  Maximum number of bit splits to test (default: 3)

I believe this should be "0-9" instead of "0-3".

**Comment by MegaByte** [comment]
Yes, this is technically true. This could even go up to 10 for 8-bit precision and 13 otherwise according to the codec source. The lower max here originally came from common JPEG header documentation that seems to be incorrectly repeated -- the idea that this value is split into high and low nibbles. However, I kept it because in my testing, I never found a compression benefit to running higher than 3. Let me know if you have examples where a higher value helps!

**Comment by MegaByte** [comment]
I now allow everything that jpegtran allows. I'd love to hear if it's ever useful though!
